[technote]
id = "SITCOMTN-119"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-119.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-119"
github_default_branch = "main"
date_created = 2024-03-13T12:41:59Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Marc"
name.family = "Moniez"
internal_id = "moniezm"

[[technote.authors.affiliations]]
name = "Laboratoire de l'Accélérateur Linéaire"
internal_id = "Paris-LAL"
address = "CNRS/IN2P3, Université de Paris-Sud, B.P. 34, 91898 Orsay Cedex, France"
